import { Inter } from "next/font/google";
import "./globals.scss";
import Header from "@/src/components/header/Header";
import Footer from "@/src/components/footer/Footer";
import { amiri } from "@/src/utils/fonts";
import { palanquin } from "@/src/utils/fonts";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${amiri.variable} ${palanquin.variable}`}>
        <Header></Header>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
